language: python

python:
  - "2.7"
  - "3.8"
  - "nightly"

install:
  - pip install -r requirements.txt

before_install:
  - sudo apt update -y -q

script:
  - python -m unittest -v ghost_protocol_test.py

dist: bionic
